# Generated by Django 5.0.14 on 2026-06-18 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('date', models.DateField(help_text='The date for these statistics', unique=True)),
                ('total_views', models.PositiveIntegerField(default=0, help_text='Total page views for the day')),
                ('unique_visitors', models.PositiveIntegerField(default=0, help_text='Unique visitors for the day')),
                ('search_count', models.PositiveIntegerField(default=0, help_text='Total searches for the day')),
                ('most_viewed_language', models.ForeignKey(blank=True, help_text='Most viewed language for the day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_viewed_days', to='languages.language')),
            ],
            options={
                'db_table': 'analytics_dailystats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('query', models.CharField(help_text='The search query string', max_length=500)),
                ('results_count', models.PositiveIntegerField(default=0, help_text='Number of results returned')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the searcher', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
            ],
            options={
                'db_table': 'analytics_searchquery',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query', 'created_at'], name='analytics_s_query_ee884c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the viewer', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('referrer', models.URLField(blank=True, help_text='Referrer URL')),
                ('path', models.CharField(help_text='URL path that was viewed', max_length=500)),
                ('language', models.ForeignKey(blank=True, help_text='Language that was viewed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='languages.language')),
                ('section', models.ForeignKey(blank=True, help_text='Section that was viewed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='content.section')),
                ('subsection', models.ForeignKey(blank=True, help_text='Subsection that was viewed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='content.subsection')),
            ],
            options={
                'db_table': 'analytics_pageview',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['language', 'created_at'], name='analytics_p_languag_a69e0d_idx'), models.Index(fields=['section', 'created_at'], name='analytics_p_section_d80df4_idx'), models.Index(fields=['created_at'], name='analytics_p_created_4c2b45_idx')],
            },
        ),
    ]
