# Generated by Django 5.0.14 on 2026-06-18 15:19

import apps.common.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('title', models.CharField(help_text='Section title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=200, validators=[apps.common.validators.validate_slug])),
                ('description', models.TextField(blank=True, help_text='Section description')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order for display')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('archived', 'Archived')], db_index=True, default='active', help_text='Publication status', max_length=20)),
                ('language', models.ForeignKey(help_text='The language this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='languages.language')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'content_section',
                'ordering': ['display_order', 'title'],
                'unique_together': {('language', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('title', models.CharField(help_text='Subsection title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=200, validators=[apps.common.validators.validate_slug])),
                ('description', models.TextField(blank=True, help_text='Subsection description')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order for display')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('archived', 'Archived')], db_index=True, default='active', help_text='Publication status', max_length=20)),
                ('section', models.ForeignKey(help_text='The section this subsection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='content.section')),
            ],
            options={
                'verbose_name': 'Subsection',
                'verbose_name_plural': 'Subsections',
                'db_table': 'content_subsection',
                'ordering': ['display_order', 'title'],
                'unique_together': {('section', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('code', 'Code'), ('table', 'Table'), ('note', 'Note'), ('warning', 'Warning'), ('tip', 'Tip'), ('image', 'Image'), ('output', 'Output'), ('divider', 'Divider'), ('quiz', 'Quiz'), ('mcq', 'MCQ'), ('roadmap', 'Roadmap'), ('video', 'Video'), ('download', 'Download')], db_index=True, help_text='Type of content', max_length=20)),
                ('data', models.JSONField(default=dict, help_text='Content data in JSON format')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order for display')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('archived', 'Archived')], db_index=True, default='active', help_text='Publication status', max_length=20)),
                ('subsection', models.ForeignKey(help_text='The subsection this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='content.subsection')),
            ],
            options={
                'verbose_name': 'Content Item',
                'verbose_name_plural': 'Content Items',
                'db_table': 'content_contentitem',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
