from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('content', '0001_initial'), ('languages', '0001_initial')]
    operations = [
        migrations.CreateModel(name='LearningProfile', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)), ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('xp', models.PositiveIntegerField(default=0)), ('current_streak', models.PositiveIntegerField(default=0)), ('last_activity_date', models.DateField(blank=True, null=True)), ('last_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='languages.language')), ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL))], options={'db_table': 'learning_profile'}),
        migrations.CreateModel(name='TopicCompletion', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)), ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='content.subsection')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_topics', to=settings.AUTH_USER_MODEL))], options={'db_table': 'learning_topic_completion'}),
        migrations.CreateModel(name='SavedContent', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)), ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='content.contentitem')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_content', to=settings.AUTH_USER_MODEL))], options={'db_table': 'learning_saved_content'}),
        migrations.CreateModel(name='LanguageNote', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)), ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('body', models.TextField(blank=True)), ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_notes', to='languages.language')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_notes', to=settings.AUTH_USER_MODEL))], options={'db_table': 'learning_language_note'}),
        migrations.CreateModel(name='LearningActivity', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)), ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('kind', models.CharField(max_length=30)), ('action_key', models.CharField(max_length=255)), ('xp_awarded', models.PositiveIntegerField(default=0)), ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='languages.language')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_activities', to=settings.AUTH_USER_MODEL))], options={'db_table': 'learning_activity'}),
        migrations.AddConstraint(model_name='topiccompletion', constraint=models.UniqueConstraint(fields=('user', 'subsection'), name='unique_user_topic_completion')),
        migrations.AddConstraint(model_name='savedcontent', constraint=models.UniqueConstraint(fields=('user', 'content_item'), name='unique_user_saved_content')),
        migrations.AddConstraint(model_name='languagenote', constraint=models.UniqueConstraint(fields=('user', 'language'), name='unique_user_language_note')),
        migrations.AddConstraint(model_name='learningactivity', constraint=models.UniqueConstraint(fields=('user', 'kind', 'action_key'), name='unique_user_learning_activity')),
    ]
