# Generated by Django 5.0.14 on 2026-06-18 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('language', models.CharField(help_text='Programming language', max_length=50)),
                ('code', models.TextField(help_text='Source code that was executed')),
                ('output', models.TextField(blank=True, help_text='Execution output')),
                ('error', models.TextField(blank=True, help_text='Execution error if any')),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('memory_used', models.IntegerField(blank=True, help_text='Memory used in KB', null=True)),
                ('status', models.CharField(default='pending', help_text='Execution status', max_length=20)),
                ('judge0_token', models.CharField(blank=True, help_text='Judge0 submission token', max_length=100)),
            ],
            options={
                'db_table': 'playground_codeexecution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportedLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Language name', max_length=50, unique=True)),
                ('judge0_id', models.IntegerField(help_text='Judge0 language ID', unique=True)),
                ('version', models.CharField(blank=True, help_text='Language version', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this language is available')),
            ],
            options={
                'db_table': 'playground_supportedlanguage',
                'ordering': ['name'],
            },
        ),
    ]
