# Generated by Django 5.0.14 on 2026-06-18 15:19

import apps.common.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('username', models.CharField(help_text='Unique username for login', max_length=50, unique=True, validators=[apps.common.validators.validate_username])),
                ('email', models.EmailField(help_text='Email address', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='First name', max_length=50)),
                ('last_name', models.CharField(blank=True, help_text='Last name', max_length=50)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('editor', 'Editor'), ('user', 'User')], db_index=True, default='user', help_text='User role for access control', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the user account is active')),
                ('is_staff', models.BooleanField(default=False, help_text='Whether the user can access the admin site')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_user',
                'ordering': ['-created_at'],
            },
        ),
    ]
