# Generated by Django 5.0.14 on 2026-06-18 15:19

import apps.common.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Language name (e.g., Python, JavaScript)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True, validators=[apps.common.validators.validate_slug])),
                ('description', models.TextField(blank=True, help_text='Brief description of the language')),
                ('icon', models.ImageField(blank=True, help_text='Language icon image', null=True, upload_to='languages/icons/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('archived', 'Archived')], db_index=True, default='active', help_text='Publication status', max_length=20)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order for display')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'languages_language',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
