export const contentTypes = [
  { value: "heading", label: "Heading" },
  { value: "paragraph", label: "Paragraph" },
  { value: "code", label: "Code" },
  { value: "table", label: "Table" },
  { value: "note", label: "Note" },
  { value: "warning", label: "Warning" },
  { value: "tip", label: "Tip" },
  { value: "output", label: "Output" },
  { value: "divider", label: "Divider" },
  { value: "image", label: "Image" },
];

export const emptyForm = {
  name: "",
  slug: "",
  description: "",
  display_order: 0,
  status: "active",
  language: "",
  section: "",
  subsection: "",
  type: "code",
  data: {},
  codeData: "",
  headingText: "",
  paragraphText: "",
  noteText: "",
  warningText: "",
  tipText: "",
  outputText: "",
  tableColumns: "",
  tableRows: "",
  imageUrl: "",
  imageAlt: "",
};
